partitions:
  parsed: "${partitions.parsed}"

train_fraction: 0.8
random_state: 3
target_column: species
test: default

# NOTE: parameter overwrites only at shallow level
nested:
  k1: base
  k2: base

sagemaker:
  model_desc: test
  model_url: s3://k9-kedro-on-aws/sagemaker/models/
  model_group_name: test
  model_group_desc: test
  model_name_base: iris-model
  image_uri: 069566694064.dkr.ecr.ap-southeast-1.amazonaws.com/sagemaker-scikit-learn:1.2-1
